### ISSUE TITLE
Build with -Werror=return-type

### ISSUE THREAD

**Issue by jengelh** [gap-packages/guava#87] opened 2023-01-03 22:50 UTC
When -Werror=return-type is used, the following problem spots are identified:

```
cc  -Werror=return-type -O2 -c   ./src/cuprstab.c 
./src/cuprstab.c: In function ‘uPartnStabRefine’:
./src/cuprstab.c:304:1: error: no return statement in function returning non-void [-Werror=return-type]
  304 | }
      | ^
./src/cuprstab.c: In function ‘PaStbR’:
./src/cuprstab.c:495:1: error: no return statement in function returning non-void [-Werror=return-type]
  495 | }
      | ^
./src/cuprstab.c: In function ‘UprStb’:
./src/cuprstab.c:128:1: error: control reaches end of non-void function [-Werror=return-type]
  128 | }
      | ^
./src/cuprstab.c: In function ‘UPrImg’:
./src/cuprstab.c:186:1: error: control reaches end of non-void function [-Werror=return-type]
  186 | }
      | ^
```

**Comment by fingolfin** [comment] 2024-01-29 23:30
Duplicate of #86

**Closed by fingolfin** 2024-01-29 23:30 UTC
